# Generated by Django 4.0.2 on 2022-02-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BroaderIndex',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('indices', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'broader_index',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Commodities',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('com_sym', models.TextField()),
                ('com_description', models.TextField()),
            ],
            options={
                'db_table': 'commodities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuLmeCsp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('rate', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cu_lme_csp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cur_symbol', models.TextField(unique=True)),
                ('cus_des', models.TextField()),
            ],
            options={
                'db_table': 'currency',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FoStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fo_status', models.IntegerField()),
            ],
            options={
                'db_table': 'fo_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndexPrice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'index_price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RbiExchange',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('rate', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rbi_exchange',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sector', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sector',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SectorialIndex',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sector', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sectorial_index',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'stock_price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=100, unique=True)),
                ('company', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'stocks',
                'managed': False,
            },
        ),
    ]
